name: Maven Build

on:
  push:
    branches:
      - main    
  pull_request:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checando código do repositório
      uses: actions/checkout@v2

    - name: Configurar JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' 
        distribution: 'temurin'  

    - name: Rodar o build Maven
      run: mvn clean install --no-transfer-progress
